### PR TITLE
Using logo without background

### PR DESCRIPTION
**Pull request by ByteHamster**
Shadow of the icon was cut off.

Before/after:

### CODE REVIEW

**Comment by keunes** [comment]
The same issue plays up in Google Play. Therefore I'd say it gets fixed together with https://github.com/AntennaPod/AntennaPod/issues/1281

**Comment by ByteHamster** [comment]
I still don't think that we should change the overall appearance of the icon. Updating on Google Play is easy, we can just make the background blue.

**Comment by keunes** [comment]
@ByteHamster What's the hex code of the Google play icon background? I have the impression it's darker than what's currently used on the site as the main colour. I think the two should be aligned (as well as in the app, actually. (and i still think the icon should get a tiny refresh, but that's another discussion so this should be merged)

**Comment by ByteHamster** [comment]
Unfortunately, we are currently quite inconsistent about the color. The app needs some updates in that regard, too (different colors in different pages).

**Pull request merged**
