### PR TITLE
fix(html): duplicate id

### PR DESCRIPTION
**Pull request by Rotzbua**
Error: Duplicate ID navbarDropdown.
Source: Nu Html Checker

### CODE REVIEW

**Comment by keunes** [comment]
What I'm wondering here, is why we have the language dropdown twice in the first place. I believe one is for mobile view, the other 'desktop'. Wouldn't it be better to 'merge' them (code-wise), if possible?

**Comment by ByteHamster** [comment]
Is this maybe also something we could change with the new website design?

**Comment by Rotzbua** [comment]
@keunes Yes there are two language dropdowns. One for mobile and one for desktop. Since it is a very simple fix, I see no reason to wait until a future solution (refactor, new design) implement it.

**Comment by keunes** [comment]
> Since it is a very simple fix, I see no reason to wait until a future solution (refactor, new design) implement it.

Fair enough.

@ByteHamster I agreed initially that this could be addressed with the website update. But we're probably going to get raw HTML+CSS and would have to translate it into Jekyll+SASS ourselves (if I understood correctly). Meaning we might just take/implement the CSS changes and update the Jekyll includes/templates (rather than reconverting from scratch). In that scenario we'd probably have to refactor the mobile menu separately.

@Rotzbua Would it be feasible for you to refactor the language menu now? If yes, I think that'd be great. If not, can you please force push to resolve the conflict?

**Pull request merged**
