### PR TITLE
Ignore link on link checker

### PR DESCRIPTION
**Pull request by ByteHamster**
Uses cloudflare redirects

### CODE REVIEW

**Comment by keunes** [comment]
@ByteHamster I think these links should be updated still? The links are effectively changed (even though they redirect). I think I updated the source, but it might not have been updated in all languages yet.
Current URL: https://www.ethnologue.com/insights/ethnologue200/

**Comment by ByteHamster** [comment]
Ooh, that's what is going on. I somehow missed that. Then I guess we should revert this PR?

**Comment by keunes** [comment]
I suspect so, yes.

Also, about this one:
Errors in _site/es/blog/2022/10/2-7-release.html
    [403] https://pixabay.com/de/users/anne-onyme-1513318/

Fine to exclude pixabay & pexels, but this (and similar) should be corrected still (es AntennaPod site links to de pixabay site)

**Comment by keunes** [comment]
All localised links updated on Weblate. If you revert this and we pull updated translations before the next link checker run, ethnologue should no longer cause trouble.

**Comment by ByteHamster** [comment]
Reverted and pulled the translations :) Let's see if the link checker runs through

**Pull request merged**
