### PR TITLE
Add optional dark mode

### LINKED ISSUE #60: Add dark theme
We have a media query for that https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

I can do it.

### PR DESCRIPTION
**Pull request by vitaly-zdanevich**
Closes #60

### CODE REVIEW

**Comment by ByteHamster** [comment]
Thanks for working on this. I made a few screenshots of pages that still need some improvements. In general, please try to avoid `!important` statements. For color schemes, please have a look at our branding repo: https://github.com/AntennaPod/Branding



- Download button has unreadable font color
- Download button no longer uses the brand color
- Menu items do not use a brand color
- Phone border is too bright



- Copyright unreadable



- Headings unreadable
- Menu item highlight color does not match the color scheme



- Mobile menu not styled
- Mobile menu icon invisible
- Link font does not match the color scheme

**Comment by vitaly-zdanevich** [comment]
Why not `!important`? Against them I can move out **light** code into `@media (prefers-color-scheme: light)`

**Comment by vitaly-zdanevich** [comment]
> Download button no longer uses the brand color

No, its still the same `#177ef0` from `.hero`.

**Comment by ByteHamster** [comment]
> Why not !important?

Usually, values that are specified further down in the css file or are more specific overwrite other values automatically. If the values are not overridden and you need `!important`, chances are high you forgot a use-case that is still not styled properly.

**Comment by ByteHamster** [comment]
> No, its still the same `#177ef0` from .hero.

Woah, interesting. In the light theme, logo color and button color look the same to me (even if you are right - it's different colors). In the dark theme, they look noticeably different.

**Comment by vitaly-zdanevich** [comment]
> > No, its still the same `#177ef0` from .hero.
> 
> Woah, interesting. In the light theme, logo color and button color look the same to me (even if you are right - it's different colors). In the dark theme, they look noticeably different.

There balls are the same color :)
image

**Comment by vitaly-zdanevich** [comment]
> Headings unreadable

What do you mean? Where?

**Comment by vitaly-zdanevich** [comment]
> > Why not !important?
> 
> Usually, values that are specified further down in the css file or are more specific overwrite other values automatically. If the values are not overridden and you need `!important`, chances are high you forgot a use-case that is still not styled properly.

Now `!important` is only for two selectors from Bootstrap.

**Comment by vitaly-zdanevich** [comment]
Fixed your feedback, please check.

I think we need dark screenshots for the main - I can do it with any podcast thumbnails inside? And maybe proportion of my phone is not identical to your..

**Comment by keunes** [comment]
@vitaly-zdanevich Please see here for the screenshots: https://github.com/AntennaPod/Branding/tree/master/Screenshots
As written there, the database available there should be used. Valid point about screen size - last time I offered to make screenshots it was decided that it's better to keep existing screen size, so ByteHamster did it then. I'll let him confirm this case.

**Comment by ByteHamster** [comment]
To be honest, I don't think we should create dedicated screenshots for the dark theme. That doubles the amount of work to keep them up-to-date and translated into all languages.

**Comment by vitaly-zdanevich** [comment]
> Please see here for the screenshots: https://github.com/AntennaPod/Branding/tree/master/Screenshots

I found dark screenshot from here  

https://github.com/AntennaPod/Branding/blob/master/Screenshots/raw/en-US/03b.png

**Comment by vitaly-zdanevich** [comment]
So what about CSS? Its done?

**Comment by vitaly-zdanevich** [comment]
And this is strange that now on main we have two identical screenshots:

image

**Comment by keunes** [comment]
> And this is strange that now on main we have two identical screenshots

I think it was added as a placeholder. The new site went live late last year, but many of the [ideas](https://forum.antennapod.org/t/sitemap-for-the-new-website/240?u=keunes) didn't get to be implemented (yet) – I think this is one of the points that was left also.

**Comment by ByteHamster** [comment]
> I found dark screenshot from here

Please just keep the light one. When we later add more screenshots, this will be a huge amount of work to keep both themes updated.

> I think it was added as a placeholder.

Yeah, I just used the same image again because I wanted to get the new website design with the new logo out as quickly as possible. No one has complained yet, so I guess it's okay to keep using the same image until I have some more time :smile: 

> Headings unreadable
>> What do you mean? Where?

The contrast of the headings is really low. On my device, they are basically unreadable when there is light in the room. Please ensure WCAG AAA contrast for all UI elements (see https://webaim.org/resources/contrastchecker/).

image

> So what about CSS? Its done?

- The dropdown button of the language selector should be inverted, too
- The link color of blog post authors is unreadable
- Links and icons on the documentation pages are really hard to read
- Maybe it's just my monitor but I can barely see the difference between the header background color and the page background color (was light blue before and is now full black)
- I think the contrast of the main fonts is a bit low. I would change the main font color to at least `#ddd`.

**Comment by vitaly-zdanevich** [comment]
About `About` in the header: in Firefox devtools I see it **AAA** by WCAG.

image

**Comment by vitaly-zdanevich** [comment]
Done all your feedback, please check.

**Comment by ByteHamster** [comment]
I like the new header background color :+1:

> About About in the header: in Firefox devtools I see it AAA by WCAG.

I meant the title of the page that is displayed when clicking the menu item.

The normal text of the about page should use `#ddd` instead of `#bbb` like on the main page.

**Comment by vitaly-zdanevich** [comment]
Done:

image

**Comment by ByteHamster** [comment]
> The normal text of the about page should use `#ddd` instead of `#bbb` like on the main page.

This is still missing. Also, the contrast of the headings on the "contribute" page are pretty low.

I think it would be great if you could move the dark theme code to its own css file (and use `@include` in the existing file). Helps to make the code a bit more modular.

**Comment by vitaly-zdanevich** [comment]
> the contrast of the headings on the "contribute" page are pretty low

Where?

image

**Comment by ByteHamster** [comment]
> Where?

The headings of the cards. I can barely read them (or is this just my monitor?). See image below.

image

Thanks for moving to a new file. For a consistent code style, could you please ensure that there always is an empty line between two css blocks in your new code?

```
x {
    ...
}
HERE
y {
    ...
}
```

**Comment by vitaly-zdanevich** [comment]
Done, please check.

**Comment by ByteHamster** [comment]
Sorry for the delay. I took a few days off AntennaPod development. Thanks for formatting the code and moving it. There still are headings with low contrast left (on the documentation page). See the screenshot below.

image

**Comment by vitaly-zdanevich** [comment]
Done:

image

**Comment by ByteHamster** [comment]
Thanks! Looks good to me now.

**Pull request merged**
