### PR TITLE
other-platforms.md add about Genymotion, Waydroid, Bliss OS

### PR DESCRIPTION
**Pull request by vitaly-zdanevich**

### CODE REVIEW

**Review by ByteHamster — COMMENTED** [review]
Thanks, I added some comments below

**Review by vitaly-zdanevich — COMMENTED** [review]
Solve the feedback - move to introduction, drop BlissOS

**Review by vitaly-zdanevich — COMMENTED** [review]
Typo of -> or

**Comment by vitaly-zdanevich** [comment]
Ok, but if somebody tries to port to Linux - is it difficult? Where to start?

**Comment by keunes** [comment]
Hi @vitaly-zdanevich
Thanks for contributing to AntennaPod!

To be honest I'm not convinced this should be merged. It's complicated for the average user to do (while those really interested in it will be able to find these tools via a web search or ask us on the forum), it's currently unclear what these do/what these are, at least Genymotion is not open source, and I'm a bit afraid that if we start recommending installing & running AntennaPod in unofficial ways we might get related support questions.

WDYT @ByteHamster?

**Comment by ByteHamster** [comment]
Hmm, right. I do have to agree that running an Android emulator just to use AntennaPod on the desktop probably is not a nice user experience. So we maybe shouldn't recommend this on the website.

**Comment by keunes** [comment]
Thanks @vitaly-zdanevich for thinking of us and preparing a pull request! As discussed, this probably isn't fit for our main website audience, so closing.

**Pull request closed without merging**
