### PR TITLE
Reword sync docs to avoid confusion over servers and hosts(#183)

### PR DESCRIPTION
**Pull request by Aliervo**
I reworded and re-ordered things to hopefully clear up some of the confusion as seen in #183. I also took a few in-app screenshots that I thought might help, but then decided that they would probably just end up bloating the page without actually adding much.  Happy to add them in if they are desirable.

### CODE REVIEW

**Comment by keunes** [comment]
Hi @Aliervo,

Many thanks for your PR. I just had a look.

I like the refinements in the first two paragraphs.
> We strongly recommend that more technical users start self-hosting using either Nextcloud and gPodder Sync or their own gpodder service from the [github repo](https://github.com/gpodder).

This feels unbalanced: we are referring people to the GitHub repo of gPodder.net, but not of Nextcloud. We should redirect to both or to none. If we do want to add links, I would link to the installation instructions of each service.
* gpodder.net: https://gpoddernet.readthedocs.io/en/latest/dev/installation.html
* Nextcloud: https://nextcloud.com/yourdata/ or https://nextcloud.com/install/#instructions-server

Then, I'm not sure about the reorganisation of the instructions themselves. I understand that it is now a single flow, with 'conditional' sections (only if gPodder.net...). However, as a consequence, if you're using Nextcloud, you have to skim a lot of text/page just to read 2 lines:
Screenshot 2022-10-26 at 09-07-00 How to synchronize between devices – AntennaPod

I would rather revert those changes, and keep the current separation between gPodder and Nextcloud. It is much faster to go through if you're a Nextcloud user and for all users takes away the reflection about each condition.

Lastly, I think it would be great if we could still address the notes in the issue you referred to:
* _Describe that synchronisation must happen via a central point, a server. That these servers can be offered by big parties shared by many users (risk: slow if not funded). Or that you can self-host a server (downside: more effort)._ --> This I guess best goes in the introduction, or at least the first point (need of a central server) - the rest is already kinda covered in the sentences about why gPodder often leads to errors.
* _Describe that 'address of webserver' is the URL of the server on which you have an account._ --> This you already covered in brackets, but I think we can make it more prominent. For example by splitting it off into a separate sentence.

Would you be OK with following up on these comments?

**Comment by Aliervo** [comment]
Thanks for the feedback, I'll make a few edits!

> This feels unbalanced: we are referring people to the GitHub repo of gPodder.net, but not of Nextcloud. We should redirect to both or to none. If we do want to add links, I would link to the installation instructions of each service.
>
> 
> * gpodder.net: https://gpoddernet.readthedocs.io/en/latest/dev/installation.html
> * Nextcloud: https://nextcloud.com/yourdata/ or https://nextcloud.com/install/#instructions-server

I feel like I meant to do this and just forgot about poor Nextcloud. Also, I got a little confused with the gPodder installation instructions because they seem relatively straightforward there, but on then I looked at the GitHub and noticed some repos related to mygpo, namely "feedservice" and "auth", and I wasn't sure if all three services or just the main repo would be needed to get sync working. I'll try to get it running to figure out what exactly to link.

> Then, I'm not sure about the reorganisation of the instructions themselves. I understand that it is now a single flow, with 'conditional' sections (only if gPodder.net...). However, as a consequence, if you're using Nextcloud, you have to skim a lot of text/page just to read 2 lines: Screenshot 2022-10-26 at 09-07-00 How to synchronize between devices – AntennaPod
> 
> I would rather revert those changes, and keep the current separation between gPodder and Nextcloud. It is much faster to go through if you're a Nextcloud user and for all users takes away the reflection about each condition.

I also noticed this once I got it all together. It almost made me want to change the first part to "Just use Nextcloud, it's easier." :rofl:

Gonna try to figure out mygpo installation, expect some edits soon-ish. :+1:

**Comment by keunes** [comment]
> Just use Nextcloud, it's easier.


Hehehe. We can indicate that indirectly, by putting it first & short :)

**Comment by Aliervo** [comment]
@keunes, I think this might be the ticket. I re-wrote the intro to be pretty explicit about servers and hostnames and added more links.  I didn't quite revert the changes to the actual instructions, but instead broke the gPodder specific "Set-up steps" to their own section below the "main steps" so we can maintain one flow, while preventing the Nextcloud folks from having to read most of the page to find what is relevant to them.

I was not able to set up my own ``mygpo`` server because all the instructions and even the scripts it uses are Ubuntu/Debian based; I am currently on Arch and didn't want to waste all night figuring out what the Arch equivalents of all the libs are, but I linked the page anyway.  If we get complaints, we might just have to write our own guide or specifically request Nextcloud. 

My only concern with Nextcloud link/instructions is that they put "Sign up with a provider" higher on the page than the actual self-hosting options, which I don't believe allows installing custom apps. My hope is that people tech-savvy enough to self-host will be smart enough to choose the correct option for their situation.

Let me know if there is anything I missed!

**Comment by keunes** [comment]
Hi @Aliervo,

Sorry for not getting back to you earlier. I had another look today and I still think that having two sections with cross-references between them is not user friendly. So I took the liberty to change the approach again, even though it leads to somewhat longer texts. I have also adjusted the text based on https://github.com/AntennaPod/AntennaPod/pull/6213.

> My only concern with Nextcloud link/instructions is that they put "Sign up with a provider" higher on the page than the actual self-hosting options, which I don't believe allows installing custom apps.

The page currently doesn't describe this option. I was hesitating to add it, but given the limitation you describe with app installations and the fact that we have no idea if/how this works, I decided to leave it out for now. Someone on the forum did indicate they were looking into this option: https://forum.antennapod.org/t/some-help-with-sync-please/2524. Maybe if we get some results/information from that, we can add this option as a second bullet point.

If you are OK with it as well, I am happy to merge this as soon as the next AntennaPod version gets released when the PR I linked gets available to everyone (hopefully early next year).

**Pull request merged**
